using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using VAWCV5Tubod.Connection;
using VAWCV5Tubod.Domain;

namespace VAWCV5Tubod
{
    public partial class FileACase : Form
    {
        private enum ImageSourceChoice
        {
            None,
            Upload,
            Camera
        }

        private const int ContactNumberMaxDigits = 11;

        private const string Ra9262ViolationText =
            "R.A. 9262: Anti Violence Against Women and their Children Act";

        private readonly string currentUsername;

        public FileACase()
            : this(string.Empty)
        {
        }

        public FileACase(string currentUsername)
        {
            this.currentUsername = currentUsername;
            InitializeComponent();
            Load += FileACase_Load;
            FormClosed += FileACase_FormClosed;
            imgComplainantbtn.Click += imgComplainantbtn_Click;
            imgRespodentBtn.Click += imgRespodentBtn_Click;
            case_ra_violation.SelectedIndexChanged += case_ra_violation_SelectedIndexChanged;
            case_ra_violation.TextChanged += case_ra_violation_TextChanged;
            comp_birthdate.ValueChanged += comp_birthdate_ValueChanged;
            resp_birthdate.ValueChanged += resp_birthdate_ValueChanged;
            comp_age.ReadOnly = true;
            resp_age.ReadOnly = true;
            AttachNumericOnlyHandlers(comp_age);
            AttachNumericOnlyHandlers(comp_contactnumber, ContactNumberMaxDigits);
            AttachNumericOnlyHandlers(resp_age);
            AttachNumericOnlyHandlers(resp_contactnumber, ContactNumberMaxDigits);
        }

        private void FileACase_Load(object? sender, EventArgs e)
        {
            label6.Text = AutoGeneratedCaseId.GetPhilippineDateToday();
            comp_image.SizeMode = PictureBoxSizeMode.Zoom;
            resp_image.SizeMode = PictureBoxSizeMode.Zoom;
            LoadPurokOptions();
            ToggleRa9262SubViolations();
            UpdateAgeFields();

            try
            {
                label4.Text = AutoGeneratedCaseId.GenerateCaseId();
            }
            catch
            {
                label4.Text = "Unavailable";
            }
        }

        private void imgComplainantbtn_Click(object? sender, EventArgs e)
        {
            ChooseAndLoadImage(comp_image);
        }

        private void imgRespodentBtn_Click(object? sender, EventArgs e)
        {
            ChooseAndLoadImage(resp_image);
        }

        private void ChooseAndLoadImage(PictureBox targetPictureBox)
        {
            ImageSourceChoice choice = PromptForImageSource();

            switch (choice)
            {
                case ImageSourceChoice.Upload:
                    BrowseAndLoadImage(targetPictureBox);
                    break;
                case ImageSourceChoice.Camera:
                    CaptureAndLoadImage(targetPictureBox);
                    break;
            }
        }

        private ImageSourceChoice PromptForImageSource()
        {
            using Form promptForm = new()
            {
                Text = "Select Image Source",
                StartPosition = FormStartPosition.CenterParent,
                FormBorderStyle = FormBorderStyle.FixedDialog,
                MaximizeBox = false,
                MinimizeBox = false,
                ClientSize = new Size(445, 150)
            };

            Label promptLabel = new()
            {
                Text = "How would you like to add the photo?",
                AutoSize = false,
                TextAlign = ContentAlignment.MiddleCenter,
                Font = new Font("Arial", 11F, FontStyle.Regular),
                Location = new Point(20, 20),
                Size = new Size(405, 35)
            };

            Button uploadButton = new()
            {
                Text = "Upload Existing Photo",
                DialogResult = DialogResult.Yes,
                Location = new Point(25, 82),
                Size = new Size(155, 35)
            };

            Button cameraButton = new()
            {
                Text = "Capture New Photo",
                DialogResult = DialogResult.No,
                Location = new Point(190, 82),
                Size = new Size(150, 35)
            };

            Button cancelButton = new()
            {
                Text = "Cancel",
                DialogResult = DialogResult.Cancel,
                Location = new Point(350, 82),
                Size = new Size(70, 35)
            };

            promptForm.Controls.AddRange(new Control[] { promptLabel, uploadButton, cameraButton, cancelButton });
            promptForm.AcceptButton = uploadButton;
            promptForm.CancelButton = cancelButton;

            return promptForm.ShowDialog(this) switch
            {
                DialogResult.Yes => ImageSourceChoice.Upload,
                DialogResult.No => ImageSourceChoice.Camera,
                _ => ImageSourceChoice.None
            };
        }

        private void CaptureAndLoadImage(PictureBox targetPictureBox)
        {
            try
            {
                using CameraCaptureForm cameraCaptureForm = new();

                if (cameraCaptureForm.ShowDialog(this) != DialogResult.OK ||
                    cameraCaptureForm.CapturedImage is null)
                {
                    return;
                }

                Image capturedImage = new Bitmap(cameraCaptureForm.CapturedImage);
                cameraCaptureForm.CapturedImage.Dispose();
                ReplacePictureBoxImage(targetPictureBox, capturedImage);
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to capture an image from the camera.{Environment.NewLine}{ex.Message}",
                    "Camera Capture Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void BrowseAndLoadImage(PictureBox targetPictureBox)
        {
            using OpenFileDialog openFileDialog = new();
            openFileDialog.Title = "Select an image";
            openFileDialog.Filter = "Image Files|*.jpg;*.jpeg;*.png;*.bmp;*.gif";
            openFileDialog.Multiselect = false;

            if (openFileDialog.ShowDialog() != DialogResult.OK)
            {
                return;
            }

            try
            {
                Image newImage = LoadImageCopy(openFileDialog.FileName);
                ReplacePictureBoxImage(targetPictureBox, newImage);
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to load the selected image.{Environment.NewLine}{ex.Message}",
                    "Image Load Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private static Image LoadImageCopy(string filePath)
        {
            using FileStream stream = new(filePath, FileMode.Open, FileAccess.Read);
            using Image originalImage = Image.FromStream(stream);
            return new Bitmap(originalImage);
        }

        private static void ReplacePictureBoxImage(PictureBox targetPictureBox, Image newImage)
        {
            Image? previousImage = targetPictureBox.Image;
            targetPictureBox.Image = newImage;
            previousImage?.Dispose();
        }

        private void FileACase_FormClosed(object? sender, FormClosedEventArgs e)
        {
            comp_image.Image?.Dispose();
            resp_image.Image?.Dispose();
        }

        private void case_ra_violation_SelectedIndexChanged(object? sender, EventArgs e)
        {
            ToggleRa9262SubViolations();
        }

        private void case_ra_violation_TextChanged(object? sender, EventArgs e)
        {
            ToggleRa9262SubViolations();
        }

        private void comp_birthdate_ValueChanged(object? sender, EventArgs e)
        {
            UpdateAgeText(comp_birthdate, comp_age);
        }

        private void resp_birthdate_ValueChanged(object? sender, EventArgs e)
        {
            UpdateAgeText(resp_birthdate, resp_age);
        }

        private void saveACasebtn_Click(object? sender, EventArgs e)
        {
            if (!ValidateRequiredInputs())
            {
                return;
            }

            try
            {
                using MySqlConnection connection = DbConnectionFactory.CreateConnection();
                connection.Open();

                using MySqlTransaction transaction = connection.BeginTransaction();

                int complainantId = SaveComplainant(connection, transaction);
                int respondentId = SaveRespondent(connection, transaction);
                int caseId = SaveCaseData(connection, transaction, complainantId, respondentId);

                transaction.Commit();

                UserLogService.Log(
                    currentUsername,
                    "AddCase",
                    "caselist",
                    caseId,
                    $"Created new case record for {BuildFullName(comp_lastname.Text, comp_firstname.Text, comp_middlename.Text)}.");

                MessageBox.Show(
                    "Case information was saved successfully.",
                    "Save Successful",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);

                ResetFormInputs();
                RefreshGeneratedCaseDetails();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to save the case.{Environment.NewLine}{ex.Message}",
                    "Save Failed",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private int SaveComplainant(MySqlConnection connection, MySqlTransaction transaction)
        {
            Complainant complainant = new()
            {
                CompImage = ConvertImageToBytes(comp_image.Image),
                LastName = comp_lastname.Text.Trim(),
                FirstName = comp_firstname.Text.Trim(),
                MiddleName = comp_middlename.Text.Trim(),
                Sex = comp_sex.Text.Trim(),
                Age = ParseIntOrZero(comp_age.Text),
                BirthDate = comp_birthdate.Value,
                Purok = comp_purok.Text.Trim(),
                Barangay = "Tubod",
                Municipal = "Lakewood",
                Province = "Zamboanga Del Sur",
                ContactNo = comp_contactnumber.Text.Trim(),
                CivilStatus = comp_civilstatus.Text.Trim(),
                EducationalAttainment = comp_educationalattainment.Text.Trim(),
                Religion = comp_religion.Text.Trim(),
                Occupation = comp_occupation.Text.Trim(),
                Nationality = comp_nationality.Text.Trim()
            };

            const string query = """
                INSERT INTO complainant (
                    comp_image,
                    comp_lastname, comp_firstname, comp_middlename, comp_sex, comp_age,
                    comp_birthdate, comp_purok, comp_barangay, comp_municipal, comp_province,
                    comp_contactno, comp_civilstatus, comp_eduattain, comp_religion,
                    comp_occupation, comp_nationality
                )
                VALUES (
                    @comp_image,
                    @lastname, @firstname, @middlename, @sex, @age,
                    @birthdate, @purok, @barangay, @municipal, @province,
                    @contactno, @civilstatus, @eduattain, @religion,
                    @occupation, @nationality
                );
                """;

            using MySqlCommand command = new(query, connection, transaction);
            command.Parameters.Add("@comp_image", MySqlDbType.LongBlob).Value =
                complainant.CompImage is null ? DBNull.Value : complainant.CompImage;
            command.Parameters.AddWithValue("@lastname", complainant.LastName);
            command.Parameters.AddWithValue("@firstname", complainant.FirstName);
            command.Parameters.AddWithValue("@middlename", complainant.MiddleName);
            command.Parameters.AddWithValue("@sex", complainant.Sex);
            command.Parameters.AddWithValue("@age", complainant.Age);
            command.Parameters.AddWithValue("@birthdate", complainant.BirthDate);
            command.Parameters.AddWithValue("@purok", complainant.Purok);
            command.Parameters.AddWithValue("@barangay", complainant.Barangay);
            command.Parameters.AddWithValue("@municipal", complainant.Municipal);
            command.Parameters.AddWithValue("@province", complainant.Province);
            command.Parameters.AddWithValue("@contactno", complainant.ContactNo);
            command.Parameters.AddWithValue("@civilstatus", complainant.CivilStatus);
            command.Parameters.AddWithValue("@eduattain", complainant.EducationalAttainment);
            command.Parameters.AddWithValue("@religion", complainant.Religion);
            command.Parameters.AddWithValue("@occupation", complainant.Occupation);
            command.Parameters.AddWithValue("@nationality", complainant.Nationality);
            command.ExecuteNonQuery();

            return Convert.ToInt32(command.LastInsertedId);
        }

        private int SaveRespondent(MySqlConnection connection, MySqlTransaction transaction)
        {
            Respondent respondent = new()
            {
                RespImage = ConvertImageToBytes(resp_image.Image),
                LastName = resp_lastname.Text.Trim(),
                FirstName = resp_firstname.Text.Trim(),
                MiddleName = resp_middlename.Text.Trim(),
                Alias = string.Empty,
                Sex = resp_sex.Text.Trim(),
                Age = ParseIntOrZero(resp_age.Text),
                BirthDate = resp_birthdate.Value,
                Purok = resp_purok.Text.Trim(),
                Barangay = "Tubod",
                Municipal = "Lakewood",
                Province = "Zamboanga Del Sur",
                ContactNo = resp_contactnumber.Text.Trim(),
                CivilStatus = resp_civilstatus.Text.Trim(),
                EducationalAttainment = resp_educationalattainment.Text.Trim(),
                Religion = resp_religion.Text.Trim(),
                Occupation = resp_occupation.Text.Trim(),
                RelationshipToComplainant = resp_relationship_to_complainant.Text.Trim(),
                Nationality = resp_nationality.Text.Trim()
            };

            const string query = """
                INSERT INTO respondent (
                    resp_img,
                    resp_lastname, resp_firstname, resp_middlename, resp_alias, resp_sex,
                    resp_age, resp_birthdate, resp_purok, resp_barangay, resp_municipal,
                    resp_province, resp_contactno, resp_civilstatus, resp_eduattain,
                    resp_religion, resp_occupation, resp_relationshiptocomplainant,
                    resp_nationality
                )
                VALUES (
                    @resp_img,
                    @lastname, @firstname, @middlename, @alias, @sex,
                    @age, @birthdate, @purok, @barangay, @municipal,
                    @province, @contactno, @civilstatus, @eduattain,
                    @religion, @occupation, @relationshiptocomplainant,
                    @nationality
                );
                """;

            using MySqlCommand command = new(query, connection, transaction);
            command.Parameters.Add("@resp_img", MySqlDbType.LongBlob).Value =
                respondent.RespImage is null ? DBNull.Value : respondent.RespImage;
            command.Parameters.AddWithValue("@lastname", respondent.LastName);
            command.Parameters.AddWithValue("@firstname", respondent.FirstName);
            command.Parameters.AddWithValue("@middlename", respondent.MiddleName);
            command.Parameters.AddWithValue("@alias", respondent.Alias);
            command.Parameters.AddWithValue("@sex", respondent.Sex);
            command.Parameters.AddWithValue("@age", respondent.Age);
            command.Parameters.AddWithValue("@birthdate", respondent.BirthDate);
            command.Parameters.AddWithValue("@purok", respondent.Purok);
            command.Parameters.AddWithValue("@barangay", respondent.Barangay);
            command.Parameters.AddWithValue("@municipal", respondent.Municipal);
            command.Parameters.AddWithValue("@province", respondent.Province);
            command.Parameters.AddWithValue("@contactno", respondent.ContactNo);
            command.Parameters.AddWithValue("@civilstatus", respondent.CivilStatus);
            command.Parameters.AddWithValue("@eduattain", respondent.EducationalAttainment);
            command.Parameters.AddWithValue("@religion", respondent.Religion);
            command.Parameters.AddWithValue("@occupation", respondent.Occupation);
            command.Parameters.AddWithValue("@relationshiptocomplainant", respondent.RelationshipToComplainant);
            command.Parameters.AddWithValue("@nationality", respondent.Nationality);
            command.ExecuteNonQuery();

            return Convert.ToInt32(command.LastInsertedId);
        }

        private void LoadPurokOptions()
        {
            try
            {
                using MySqlConnection connection = DbConnectionFactory.CreateConnection();
                connection.Open();

                const string query = """
                    SELECT purok_name
                    FROM purok
                    WHERE purok_name IS NOT NULL AND TRIM(purok_name) <> ''
                    ORDER BY purok_id;
                    """;

                using MySqlCommand command = new(query, connection);
                using MySqlDataReader reader = command.ExecuteReader();

                List<string> purokNames = new();

                while (reader.Read())
                {
                    purokNames.Add(reader.GetString("purok_name"));
                }

                PopulatePurokComboBox(comp_purok, purokNames);
                PopulatePurokComboBox(resp_purok, purokNames);
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to load purok names.{Environment.NewLine}{ex.Message}",
                    "Purok Load Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning);
            }
        }

        private static void PopulatePurokComboBox(ComboBox comboBox, IEnumerable<string> purokNames)
        {
            comboBox.BeginUpdate();
            comboBox.Items.Clear();
            comboBox.Items.AddRange(purokNames.Cast<object>().ToArray());
            comboBox.EndUpdate();
        }

        private int SaveCaseData(MySqlConnection connection, MySqlTransaction transaction, int complainantId, int respondentId)
        {
            Caselist caseInfo = new()
            {
                CaseId = ParseIntOrZero(label4.Text),
                ComplaintDate = DateTime.TryParse(label6.Text, out DateTime complaintDate) ? complaintDate : DateTime.Now,
                CompId = complainantId,
                ComplainantFullname = BuildFullName(comp_lastname.Text, comp_firstname.Text, comp_middlename.Text),
                RespId = respondentId,
                RespondentFullname = BuildFullName(resp_lastname.Text, resp_firstname.Text, resp_middlename.Text),
                Violation = case_ra_violation.Text.Trim(),
                SubViolation = GetCheckboxValueOrEmpty(case_ra_sub_physical_abuse),
                SubViolation2 = GetCheckboxValueOrEmpty(case_ra_sub_psychological_abuse),
                SubViolation3 = GetCheckboxValueOrEmpty(case_ra_sub_sexual_abuse),
                SubViolation4 = GetCheckboxValueOrEmpty(case_ra_sub_economic_abuse),
                CaseStatus = case_status.Text.Trim(),
                ReferredTo = case_referred_to.Text.Trim(),
                PlaceOfIncident = case_incident_place.Text.Trim(),
                IncidentDate = case_incident_date.Value,
                IncidentDescription = case_incident_description.Text.Trim()
            };

            const string query = """
                INSERT INTO caselist (
                    caseId, complaintDate, compId, complainantFullname, respId, respondentFullname,
                    violation, subViolation, subViolation2, subViolation3, subViolation4,
                    casestatus, referredto, placeofincident, incidentdate, incidentdescription
                )
                VALUES (
                    @caseId, @complaintDate, @compId, @complainantFullname, @respId, @respondentFullname,
                    @violation, @subViolation, @subViolation2, @subViolation3, @subViolation4,
                    @casestatus, @referredto, @placeofincident, @incidentdate, @incidentdescription
                );
                """;

            using MySqlCommand command = new(query, connection, transaction);
            command.Parameters.AddWithValue("@caseId", caseInfo.CaseId);
            command.Parameters.AddWithValue("@complaintDate", caseInfo.ComplaintDate);
            command.Parameters.AddWithValue("@compId", caseInfo.CompId);
            command.Parameters.AddWithValue("@complainantFullname", caseInfo.ComplainantFullname);
            command.Parameters.AddWithValue("@respId", caseInfo.RespId);
            command.Parameters.AddWithValue("@respondentFullname", caseInfo.RespondentFullname);
            command.Parameters.AddWithValue("@violation", caseInfo.Violation);
            command.Parameters.AddWithValue("@subViolation", caseInfo.SubViolation);
            command.Parameters.AddWithValue("@subViolation2", caseInfo.SubViolation2);
            command.Parameters.AddWithValue("@subViolation3", caseInfo.SubViolation3);
            command.Parameters.AddWithValue("@subViolation4", caseInfo.SubViolation4);
            command.Parameters.AddWithValue("@casestatus", caseInfo.CaseStatus);
            command.Parameters.AddWithValue("@referredto", caseInfo.ReferredTo);
            command.Parameters.AddWithValue("@placeofincident", caseInfo.PlaceOfIncident);
            command.Parameters.AddWithValue("@incidentdate", caseInfo.IncidentDate);
            command.Parameters.AddWithValue("@incidentdescription", caseInfo.IncidentDescription);
            command.ExecuteNonQuery();

            return caseInfo.CaseId;
        }

        private static int ParseIntOrZero(string value)
        {
            return int.TryParse(value, out int parsedValue) ? parsedValue : 0;
        }

        private static string BuildFullName(string lastName, string firstName, string middleName)
        {
            return string.Join(
                " ",
                new[] { lastName.Trim(), firstName.Trim(), middleName.Trim() }
                    .Where(part => !string.IsNullOrWhiteSpace(part)));
        }

        private static string GetCheckboxValueOrEmpty(CheckBox checkBox)
        {
            return checkBox.Checked ? checkBox.Text : string.Empty;
        }

        private void UpdateAgeFields()
        {
            UpdateAgeText(comp_birthdate, comp_age);
            UpdateAgeText(resp_birthdate, resp_age);
        }

        private static void UpdateAgeText(DateTimePicker birthDatePicker, TextBox ageTextBox)
        {
            ageTextBox.Text = CalculateAge(birthDatePicker.Value).ToString();
        }

        private static int CalculateAge(DateTime birthDate)
        {
            DateTime today = AutoGeneratedCaseId.GetPhilippineToday();
            int age = today.Year - birthDate.Year;

            if (birthDate.Date > today.AddYears(-age))
            {
                age--;
            }

            return Math.Max(age, 0);
        }

        private bool IsRa9262Selected()
        {
            return string.Equals(
                case_ra_violation.Text.Trim(),
                Ra9262ViolationText,
                StringComparison.Ordinal);
        }

        private void ToggleRa9262SubViolations()
        {
            bool allowSubViolations = IsRa9262Selected();

            SetRaSubViolationState(case_ra_sub_physical_abuse, allowSubViolations);
            SetRaSubViolationState(case_ra_sub_psychological_abuse, allowSubViolations);
            SetRaSubViolationState(case_ra_sub_sexual_abuse, allowSubViolations);
            SetRaSubViolationState(case_ra_sub_economic_abuse, allowSubViolations);
        }

        private static void SetRaSubViolationState(CheckBox checkBox, bool enabled)
        {
            checkBox.Enabled = enabled;

            if (!enabled)
            {
                checkBox.Checked = false;
            }
        }

        private static void AttachNumericOnlyHandlers(TextBox textBox, int maxDigits = 0)
        {
            if (maxDigits > 0)
            {
                textBox.MaxLength = maxDigits;
            }

            textBox.KeyPress += NumericTextBox_KeyPress;
            textBox.TextChanged += NumericTextBox_TextChanged;
        }

        private static void NumericTextBox_KeyPress(object? sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar))
            {
                e.Handled = true;
                return;
            }

            if (char.IsDigit(e.KeyChar) &&
                sender is TextBox textBox &&
                textBox.MaxLength > 0 &&
                textBox.TextLength - textBox.SelectionLength >= textBox.MaxLength)
            {
                e.Handled = true;
            }
        }

        private static void NumericTextBox_TextChanged(object? sender, EventArgs e)
        {
            if (sender is not TextBox textBox)
            {
                return;
            }

            string originalText = textBox.Text;
            string digitsOnly = new(originalText.Where(char.IsDigit).ToArray());
            int maxDigits = textBox.MaxLength > 0 ? textBox.MaxLength : 0;

            if (maxDigits > 0 && digitsOnly.Length > maxDigits)
            {
                digitsOnly = digitsOnly.Substring(0, maxDigits);
            }

            if (originalText == digitsOnly)
            {
                return;
            }

            int selectionStart = textBox.SelectionStart;
            int removedCharactersBeforeCaret = originalText
                .Take(Math.Min(selectionStart, originalText.Length))
                .Count(character => !char.IsDigit(character));

            textBox.Text = digitsOnly;
            textBox.SelectionStart = Math.Min(
                digitsOnly.Length,
                Math.Max(0, selectionStart - removedCharactersBeforeCaret));
        }

        private bool ValidateRequiredInputs()
        {
            List<string> missingFields = new();

            ValidateRequiredText(comp_lastname, "Complainant Last Name", missingFields);
            ValidateRequiredText(comp_firstname, "Complainant First Name", missingFields);
            ValidateRequiredText(comp_middlename, "Complainant Middle Name", missingFields);
            ValidateRequiredText(comp_sex, "Complainant Sex", missingFields);
            ValidateRequiredText(comp_age, "Complainant Age", missingFields);
            ValidateRequiredText(comp_purok, "Complainant Purok", missingFields);
            ValidateRequiredText(comp_contactnumber, "Complainant Contact Number", missingFields);
            ValidateRequiredText(comp_civilstatus, "Complainant Civil Status", missingFields);
            ValidateRequiredText(comp_religion, "Complainant Religion", missingFields);
            ValidateRequiredText(comp_occupation, "Complainant Occupation", missingFields);
            ValidateRequiredText(comp_nationality, "Complainant Nationality", missingFields);
            ValidateRequiredText(comp_educationalattainment, "Complainant Educational Attainment", missingFields);

            ValidateRequiredText(resp_lastname, "Respondent Last Name", missingFields);
            ValidateRequiredText(resp_firstname, "Respondent First Name", missingFields);
            ValidateRequiredText(resp_middlename, "Respondent Middle Name", missingFields);
            ValidateRequiredText(resp_sex, "Respondent Sex", missingFields);
            ValidateRequiredText(resp_age, "Respondent Age", missingFields);
            ValidateRequiredText(resp_purok, "Respondent Purok", missingFields);
            ValidateRequiredText(resp_contactnumber, "Respondent Contact Number", missingFields);
            ValidateRequiredText(resp_civilstatus, "Respondent Civil Status", missingFields);
            ValidateRequiredText(resp_religion, "Respondent Religion", missingFields);
            ValidateRequiredText(resp_occupation, "Respondent Occupation", missingFields);
            ValidateRequiredText(resp_nationality, "Respondent Nationality", missingFields);
            ValidateRequiredText(resp_educationalattainment, "Respondent Educational Attainment", missingFields);
            ValidateRequiredText(resp_relationship_to_complainant, "Relationship To Complainant", missingFields);

            ValidateRequiredText(case_ra_violation, "R.A. Violation", missingFields);
            ValidateRequiredText(case_status, "Case Status", missingFields);
            ValidateRequiredText(case_referred_to, "Referred To", missingFields);
            ValidateRequiredText(case_incident_place, "Place Of Incident", missingFields);
            ValidateRequiredText(case_incident_description, "Incident Description", missingFields);

            if (comp_image.Image is null)
            {
                missingFields.Add("Complainant Image");
            }

            if (resp_image.Image is null)
            {
                missingFields.Add("Respondent Image");
            }

            if (IsRa9262Selected() &&
                !case_ra_sub_physical_abuse.Checked &&
                !case_ra_sub_psychological_abuse.Checked &&
                !case_ra_sub_sexual_abuse.Checked &&
                !case_ra_sub_economic_abuse.Checked)
            {
                missingFields.Add("At least one R.A. Sub Case Violation");
            }

            if (string.IsNullOrWhiteSpace(label4.Text) || label4.Text == "Unavailable")
            {
                missingFields.Add("Case ID");
            }

            if (missingFields.Count == 0)
            {
                return true;
            }

            MessageBox.Show(
                "Please complete all required fields before saving:" +
                Environment.NewLine + Environment.NewLine +
                string.Join(Environment.NewLine, missingFields.Select(field => $"- {field}")),
                "Incomplete Form",
                MessageBoxButtons.OK,
                MessageBoxIcon.Warning);

            return false;
        }

        private static void ValidateRequiredText(Control control, string fieldName, List<string> missingFields)
        {
            if (string.IsNullOrWhiteSpace(control.Text))
            {
                missingFields.Add(fieldName);
            }
        }

        private void ResetFormInputs()
        {
            ClearTextBoxes(this);
            ClearComboBoxes(this);
            ResetDateTimePickers(this);
            ClearCheckBoxes(this);
            ClearImages();
            UpdateAgeFields();
            ToggleRa9262SubViolations();
        }

        private void RefreshGeneratedCaseDetails()
        {
            label6.Text = AutoGeneratedCaseId.GetPhilippineDateToday();

            try
            {
                label4.Text = AutoGeneratedCaseId.GenerateCaseId();
            }
            catch
            {
                label4.Text = "Unavailable";
            }
        }

        private void ClearTextBoxes(Control parent)
        {
            foreach (Control control in parent.Controls)
            {
                if (control is TextBox textBox)
                {
                    textBox.Clear();
                }

                if (control.HasChildren)
                {
                    ClearTextBoxes(control);
                }
            }
        }

        private void ClearComboBoxes(Control parent)
        {
            foreach (Control control in parent.Controls)
            {
                if (control is ComboBox comboBox)
                {
                    comboBox.SelectedIndex = -1;
                    comboBox.Text = string.Empty;
                }

                if (control.HasChildren)
                {
                    ClearComboBoxes(control);
                }
            }
        }

        private void ResetDateTimePickers(Control parent)
        {
            foreach (Control control in parent.Controls)
            {
                if (control is DateTimePicker dateTimePicker)
                {
                    dateTimePicker.Value = DateTime.Now;
                }

                if (control.HasChildren)
                {
                    ResetDateTimePickers(control);
                }
            }
        }

        private void ClearCheckBoxes(Control parent)
        {
            foreach (Control control in parent.Controls)
            {
                if (control is CheckBox checkBox)
                {
                    checkBox.Checked = false;
                }

                if (control.HasChildren)
                {
                    ClearCheckBoxes(control);
                }
            }
        }

        private void ClearImages()
        {
            Image? complainantImage = comp_image.Image;
            Image? respondentImage = resp_image.Image;

            comp_image.Image = null;
            resp_image.Image = null;

            complainantImage?.Dispose();
            respondentImage?.Dispose();
        }

        private static byte[]? ConvertImageToBytes(Image? image)
        {
            if (image is null)
            {
                return null;
            }

            using MemoryStream memoryStream = new();
            image.Save(memoryStream, ImageFormat.Png);
            return memoryStream.ToArray();
        }

        private void saveACasebtn_Click_1(object sender, EventArgs e)
        {
            if (!ValidateRequiredInputs())
            {
                return;
            }

            try
            {
                using MySqlConnection connection = DbConnectionFactory.CreateConnection();
                connection.Open();

                using MySqlTransaction transaction = connection.BeginTransaction();

                int complainantId = SaveComplainant(connection, transaction);
                int respondentId = SaveRespondent(connection, transaction);
                SaveCaseData(connection, transaction, complainantId, respondentId);

                transaction.Commit();

                MessageBox.Show(
                    "Case information was saved successfully.",
                    "Save Successful",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);

                ResetFormInputs();
                RefreshGeneratedCaseDetails();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to save the case.{Environment.NewLine}{ex.Message}",
                    "Save Failed",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }
    }
}
