using System.Globalization;
using MySql.Data.MySqlClient;

namespace VAWCV5Tubod.Connection
{
    internal static class AutoGeneratedCaseId
    {
        public static string GenerateCaseId()
        {
            DateTime currentTime = GetPhilippineNow();

            int yearTwoDigits = currentTime.Year % 100;
            int monthTwoDigits = currentTime.Month;

            int prefix = (yearTwoDigits * 100) + monthTwoDigits;
            int baseId = prefix * 10000;
            int upperBound = baseId + 10000;

            const string query = """
                SELECT MAX(caseId) AS maxId
                FROM caselist
                WHERE caseId >= @base AND caseId < @upper;
                """;

            using MySqlConnection connection = DbConnectionFactory.CreateConnection();
            connection.Open();

            using MySqlCommand command = new(query, connection);
            command.Parameters.Add("@base", MySqlDbType.Int32).Value = baseId;
            command.Parameters.Add("@upper", MySqlDbType.Int32).Value = upperBound;

            object? result = command.ExecuteScalar();

            int nextId;
            if (result is null || result == DBNull.Value)
            {
                nextId = baseId + 1;
            }
            else
            {
                int maxId = Convert.ToInt32(result);
                nextId = maxId + 1;

                if (nextId >= upperBound)
                {
                    nextId = upperBound - 1;
                }
            }

            return nextId.ToString("D8", CultureInfo.InvariantCulture);
        }

        public static string GetPhilippineDateToday()
        {
            DateTime currentTime = GetPhilippineNow();
            return currentTime.ToString("MMMM dd, yyyy", CultureInfo.InvariantCulture);
        }

        public static DateTime GetPhilippineToday()
        {
            return GetPhilippineNow().Date;
        }

        private static DateTime GetPhilippineNow()
        {
            try
            {
                TimeZoneInfo philippineTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Singapore Standard Time");
                return TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, philippineTimeZone);
            }
            catch (TimeZoneNotFoundException)
            {
                return DateTime.Now;
            }
            catch (InvalidTimeZoneException)
            {
                return DateTime.Now;
            }
        }
    }
}
